openWorkoutTracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('workouttracker.urls')),
    path('admin/', admin.site.urls),
]

workouttracker/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from rest_framework import routers
from rest_framework.authtoken import views as drf_views
from workouttracker.rest import views as rest_views
from workouttracker.views import index as general_views
from workouttracker.views import routines as routine_views
from workouttracker.views import exercises as exercise_views
from workouttracker.views import workouts as workout_views
from workouttracker.views import runs as run_views


router = routers.DefaultRouter()
router.register(r'routines', rest_views.RoutineViewSet)
router.register(r'exercises', rest_views.ExerciseViewSet)
router.register(r'runs', rest_views.RunViewSet)
router.register(r'workouts', rest_views.WorkoutViewSet)

urlpatterns = [
    path('', general_views.IndexView.as_view(), name='index'),

    path('accounts/', include('allauth.urls')),

    path('routines/', routine_views.RoutineIndex.as_view(), name='routines'),
    path('workouts/', workout_views.WorkoutIndex.as_view(), name='workouts'),
    path('routines/<int:pk>/edit/',
         routine_views.RoutineExerciseUpdate.as_view(), name='routine_update'),
    path('routines/<int:pk>/asworkout/',
         workout_views.WorkoutCreateFromRoutine.as_view(), name='routine_as_workout'),
     path('routines/<int:pk>/delete/',
         routine_views.RoutineDelete.as_view(), name='routine_delete'),
    path('workouts/<int:pk>/edit/',
         workout_views.WorkoutExerciseUpdate.as_view(), name='workout_update'),
    path('workouts/<int:pk>/delete/',
         workout_views.WorkoutDelete.as_view(), name='workout_delete'),
    path('routine/create/',
         routine_views.RoutineExerciseCreate.as_view(), name='routine_create'),
    path('workout/create/',
         workout_views.WorkoutExerciseCreate.as_view(), name='workout_create'),
    path('exercise/create/',
         exercise_views.ExerciseCreate.as_view(), name='exercise_create'),
    path('exercise/<int:pk>/edit/',
         exercise_views.ExerciseUpdate.as_view(), name='exercise_update'),
    path('exercise/<int:pk>/delete/',
         exercise_views.ExerciseDelete.as_view(), name='exercise_delete'),
    path('exercises/',
         exercise_views.ExerciseIndex.as_view(), name='exercises'),
    path('runs/<int:pk>/delete/',
         run_views.RunDelete.as_view(), name='run_delete'),
    path('runs/<int:pk>/edit/',
         run_views.RunUpdate.as_view(), name='run_update'),
    path('runs/create/',
         run_views.RunCreate.as_view(), name='run_create'),
    path('runs/',
         run_views.RunIndex.as_view(), name='runs'),
    path('manifest.json', TemplateView.as_view(template_name='workouttracker/manifest.json'),
         name='manifest'),

    path('rest/', include(router.urls)),

]

workouttracker/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext as _

from workouttracker import models

class RoutineForm(forms.ModelForm):
    class Meta:
        model = models.Routine
        fields = ['name','description']
    field_order = ['name','description']

    def save(self, commit=True):
        routine = super().save(commit)
        routine.save()
        models.RoutineExercise.objects.create(routine=routine)
        return routine

class WorkoutForm(forms.ModelForm):
    class Meta:
        model = models.Workout
        fields = ['description']

    def save(self, commit=True):
        workout = super().save(commit)
        workout.save()
        models.WorkoutExercise.objects.create(workout=workout)
        return workout

class ExerciseForm(forms.ModelForm):
    class Meta:
        model = models.Exercise
        fields = ('title','dateAdded', 'description', 'sets', 'reps')

    def save(self, commit=True):
        exercise = super().save(commit)
        return exercise

class RunForm(forms.ModelForm):
    class Meta:
        model = models.Run
        fields = ('date','description', 'distance', 'time')

    def save(self, commit=True):
        run = super().save(commit)
        return run

class ExerciseSelectForm(forms.ModelForm):
    class Meta:
        model = models.Exercise
        fields = ['title', 'description','reps','sets']
        widgets = {'title' : forms.HiddenInput(), 'description' : forms.HiddenInput(),
        'reps' : forms.HiddenInput(), 'sets' : forms.HiddenInput()}
    existing_exercises = forms.ModelChoiceField(queryset=models.Exercise.objects) 

class RoutineExerciseForm(forms.ModelForm):
    class Meta:
        model = models.RoutineExercise
        fields = ['title', 'description','reps','sets']

class WorkoutExerciseForm(forms.ModelForm):
    class Meta:
        model = models.WorkoutExercise
        fields = ['title', 'description','reps','sets']

    
RoutineFormSet = forms.models.inlineformset_factory(
    models.Routine, models.RoutineExercise, form=RoutineExerciseForm, extra=1
    )

WorkoutFormSet = forms.models.inlineformset_factory(
    models.Workout, models.WorkoutExercise, form=WorkoutExerciseForm, extra=1
    )
        

workouttracker/rest/views.py
from rest_framework import views, viewsets
from rest_framework.decorators import action
from rest_framework.response import Response

from workouttracker.models import Workout, WorkoutExercise, Exercise, Routine, RoutineExercise, Run
from workouttracker.rest import serializers
from workouttracker.rest.serializers import (WorkoutSerializer,
                                           WorkoutExerciseSerializer,
                                           ExerciseSerializer, RoutineSerializer, 
                                           RoutineExerciseSerializer, RunSerializer)

class RoutineViewSet(viewsets.ModelViewSet):
    queryset = Routine.objects.all()
    serializer_class = RoutineSerializer

class ExerciseViewSet(viewsets.ModelViewSet):
    queryset = Exercise.objects.all()
    serializer_class = ExerciseSerializer

class RunViewSet(viewsets.ModelViewSet):
    queryset = Run.objects.all()
    serializer_class = RunSerializer

class WorkoutViewSet(viewsets.ModelViewSet):
    queryset = Workout.objects.all()
    serializer_class = WorkoutSerializer

workouttracker/views/exercises.py
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from workouttracker.forms import ExerciseForm
from workouttracker.models import Exercise
# from workouttracker.lib import last_day_of_month


class ExerciseDetail(LoginRequiredMixin, generic.DetailView):
    model = Exercise
    context_object_name = 'exercise'
    def get_context_data(self, **kwargs):
        context = super(ExerciseDetail, self).get_context_data(**kwargs)
        context['menu'] = 'exercises'
        return context


class ExerciseDelete(LoginRequiredMixin, generic.edit.DeleteView):
    model = Exercise
    success_url = reverse_lazy('exercises')

    def get_context_data(self, **kwargs):
        context = super(ExerciseDelete, self).get_context_data(**kwargs)
        context['menu'] = 'exercises'
        return context


class ExerciseIndex(LoginRequiredMixin, generic.ListView):
    template_name = 'workouttracker/exercises_overview.html'
    context_object_name = 'exercises'
    def get_queryset(self):
        return Exercise.objects.belongsTo(self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'exercises'
        return context


class ExerciseCreate(LoginRequiredMixin, generic.edit.CreateView):
    model = Exercise
    template_name = 'workouttracker/exercise_form.html'
    form_class = ExerciseForm

    def get_context_data(self, **kwargs):
        context = super(ExerciseCreate, self).get_context_data(**kwargs)
        context['menu'] = 'exercises'
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form(self.get_form_class())

        if form.is_valid():
            exercise = form.save(commit=False)
            exercise.user = self.request.user
            exercise.save()
            return HttpResponseRedirect(reverse('exercises'))
        return self.render_to_response(self.get_context_data(form=form))


class ExerciseUpdate(LoginRequiredMixin, generic.edit.UpdateView):
    model = Exercise
    template_name = 'workouttracker/exercise_form.html'
    form_class = ExerciseForm


    def get_context_data(self, **kwargs):
        context = super(ExerciseUpdate, self).get_context_data(**kwargs)
        context['form'] = self.form_class(**self.get_form_kwargs())
        context['menu'] = 'exercises'
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form(self.get_form_class())

        if form.is_valid():
            exercise = form.save(commit=False)
            form = self.form_class(self.request.POST, instance=exercise)
            if form.is_valid():
                exercise.save()
                form.save()
                return HttpResponseRedirect(reverse('exercises'))
        return self.render_to_response(self.get_context_data(form=form))

workouttracker/views/index.py
from datetime import date, timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models
from django.views import generic
from django.core.serializers import serialize
import jsonpickle
import json

from rest_framework.renderers import JSONRenderer
from rest_framework.authtoken.models import Token as AuthToken
from workouttracker.lib import last_day_of_month
from workouttracker.models import Workout, WorkoutExercise, Run


class IndexView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'workouttracker/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'home'
        context['workoutsTotal'] = Workout.objects.belongsTo(self.request.user).count()
        context['runsTotal'] = Run.objects.belongsTo(self.request.user).count()
        context['lastWorkout'] = Workout.objects.belongsTo(self.request.user).mostRecent()
        context['lastWorkoutExercises'] = WorkoutExercise.objects.getForWorkout(context['lastWorkout'])
        context['runTotal'] = Run.objects.belongsTo(self.request.user).totalDistance()
        context['runChartData'] = serialize('json',Run.objects.belongsTo(self.request.user).only('date'))
        context['lastRun'] = Run.objects.belongsTo(self.request.user).mostRecent()
        return context

workouttracker/views/routines.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic

from workouttracker.forms import ExerciseSelectForm, ExerciseForm, RoutineFormSet
from workouttracker.models import Exercise, Routine, RoutineExercise

import jsonpickle
from collections import namedtuple

class RoutineIndex(LoginRequiredMixin, generic.ListView):
    template_name = 'workouttracker/routine_overview.html'
    context_object_name = 'routines'
    model = Routine
    paginate_by = 50
    
    class routineEntry:
        name=''
        exercises=[]

    def get_queryset(self):
        queryset = super().get_queryset()
        
        if 'routineexercise' in self.request.GET:
            queryset = queryset.filter(routineexercise_id=self.request.GET['routineexercise'])

        return super().get_queryset()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'routines'
        context['submenu'] = 'all'
        routines = context['routines']
        routinesList = []
        for routine in routines:
            entry = self.routineEntry()
            entry.name = routine
            entry.exercises = RoutineExercise.objects.belongsTo(self.request.user).filter(routine_id=routine.id)
            routinesList.append({"name": routine, "id": routine.id, "exercises": RoutineExercise.objects.filter(routine_id=routine.id)})

        context['routinesList'] = routinesList
    
        return context

class RoutineExerciseCreate(LoginRequiredMixin, generic.edit.CreateView):
    model = Routine
    template_name = 'workouttracker/routine_form.html'
    formset_class = RoutineFormSet
    fields = ['name','description']

    def get_context_data(self, **kwargs):
        context = super(RoutineExerciseCreate, self).get_context_data(**kwargs)
        context['exerciseSelect'] = Exercise.objects.belongsTo(self.request.user)
        context['exercises'] = jsonpickle.encode(Exercise.objects.belongsTo(self.request.user))
        context['formset'] = self.formset_class()
        context['menu'] = 'routines'
        return context

    def post(self, request, *args, **kwargs):
        form = self.get_form(self.get_form_class())

        if form.is_valid():
            routine = form.save(commit=False)
            formset = self.formset_class(self.request.POST, instance=routine)
            if formset.is_valid():
                routine.user = self.request.user
                routine.save()
                new_instances = formset.save(commit=False)
                for new_instance in new_instances:
                    new_instance.user = self.request.user
                    new_instance.save()
                return HttpResponseRedirect(reverse('routines'))
        return self.render_to_response(self.get_context_data(form=form))

class RoutineExerciseUpdate(LoginRequiredMixin, generic.edit.UpdateView):
    model = Routine
    template_name = 'workouttracker/routine_form.html'
    formset_class = RoutineFormSet
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super(RoutineExerciseUpdate, self).get_context_data(**kwargs)
        context['exerciseSelect'] = Exercise.objects.belongsTo(self.request.user)
        context['exercises'] = jsonpickle.encode(Exercise.objects.belongsTo(self.request.user))
        context['formset'] = self.formset_class(**self.get_form_kwargs())
        context['menu'] = 'routines'
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form(self.get_form_class())

        if form.is_valid():
            routine = form.save(commit=False)
            formset = self.formset_class(self.request.POST, instance=routine)
            if formset.is_valid():
                routine.user = self.request.user
                routine.save()
                new_instances = formset.save(commit=False)
                for new_instance in new_instances:
                    new_instance.user = self.request.user
                    new_instance.save()
                return HttpResponseRedirect(reverse('routines'))
        return self.render_to_response(self.get_context_data(form=form))

class RoutineDelete(LoginRequiredMixin, generic.edit.DeleteView):
    model = Routine
    success_url = reverse_lazy('routines')

    def get_context_data(self, **kwargs):
        context = super(RoutineDelete, self).get_context_data(**kwargs)
        context['menu'] = 'routines'
        return context

workouttracker/templates/workouttracker/exercise_form.html
{% extends 'workouttracker/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Exercises
  <small>
    {% if object %}
    Edit
    {% else %}
    Add new 
    {% endif %}
  </small>
</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'exercises' %}">Exercises</a></li>
  {% if object %}
  <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="breadcrumb-item active">Edit</li>
  {% else %}
  <li class="breadcrumb-item active">Create</li>
  {% endif %}
</ol>
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header with-border">
    <h3 class="card-title">Exercise Details</h3>
  </div>
  <div class="card-body">
    <form method="post" class="form-horizontal">
        {% csrf_token %}
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}
          </label>
          <div class="col-sm-8">
            {% if field|widget_type == 'dateinput' %}
            {{ field|add_class:"form-control dateinput" }}
            {% else %}
            {{ field|add_class:"form-control" }}
            {% endif %}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
      <br>
      {% for error in form.non_field_errors %}
      {{ error }}
      {% endfor %}
      {{ formset.management_form }}
      <button type="submit" class="btn btn-primary col-md-offset-2">{% if object %}Update{% else %}Create{% endif %}</button>
    </form>
  </div>
</div>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'vendor/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'vendor/js/bootstrap-datepicker.min.js' %}"></script>
<script>
function cloneMore(selector) {
    var newElement = $(selector).clone(true);
    var total = $('#id_splits-TOTAL_FORMS').val();
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total - 1) + '-','-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
    });
    newElement.find('.dateinput').each(function() {
        $(this).attr("id", "").removeData().off();
        $(this).find('.add-on').removeData().off();
        $(this).find('input').removeData().off();
        $(this).datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            disableTouchKeyboard: true
          });
    });
    newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total - 1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
    });
    $('#id_splits-TOTAL_FORMS').val(++total);
    $(selector).after(newElement);
}
$(function() {
  $('.dateinput').datepicker({
    autoclose: true,
    format: 'yyyy-mm-dd',
    disableTouchKeyboard: true
  });
  $('.dateinput').attr('autocomplete', 'off');
  $('#add-split').click(function() {
    cloneMore('#formset tr:last');
  });
});
</script>
{% endblock %}

workouttracker/templates/workouttracker/exercises_overview.html
{% extends 'workouttracker/base.html' %}
{% load humanize %}

{% block content_header %}
<h1>Exercises
</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item active">Exercises</li>
</ol>
{% endblock %}

{% block content %}
<div class="card">
<div class="card-header with-border">
  <h3 class="card-title">Exercises</h3>
</div>
<div class="card-body">
<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th>Description</th>
    <th class="hidden-xs">Sets</th>
    <th class="hidden-xs">Reps</th>
    <th class="hidden-xs"></th>
  </tr>
{% for exercise in exercises %}
<tr>
  <td><a href="{{ exercise.get_absolute_url }}">{{ exercise.title }}</a></td>
  <td class="hidden-xs">{{ exercise.dateAdded }}</td>
  <td class="hidden-xs">{{ exercise.description }}</td>
  <td class="hidden-xs">{{ exercise.sets }}</td>
  <td class="hidden-xs">{{ exercise.reps }}</td>
  <form id="delete_form_{{exercise.pk}}" method="post" action="{% url 'exercise_delete' exercise.pk %}">
    {% csrf_token %}
</form>
  <td class="hidden-xs"><a href="#" onclick="document.getElementById('delete_form_{{exercise.pk}}').submit();" class="btn btn-primary">Delete</a></td>
{% endfor %}
</table>
</div>
<div class="card-footer">
  <a href="{% url 'exercise_create' %}" class="btn btn-primary">Create</a>
</div>
</div>
{% endblock %}

workouttracker/templates/workouttracker/routine_form.html
{% extends 'workouttracker/base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Routines
  <small>
    {% if object %}
    Edit {{ object.title }}
    {% else %}
    Add new {{ submenu }}
    {% endif %}
  </small>
</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item"><a href="{% url 'routines' %}">Routines</a></li>
  {% if object %}
  <li class="breadcrumb-item"><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="breadcrumb-item active">Edit</li>
  {% else %}
  <li class="breadcrumb-item active">Create</li>
  {% endif %}
</ol>
{% endblock %}

{% block content %}
<div class="card">
  <div class="card-header with-border">
    <h3 class="card-title">Routine Details</h3>
  </div>
  <div class="card-body">
    <form method="post" class="form-horizontal">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}
          </label>
          <div class="col-sm-8">
            {% if field|widget_type == 'dateinput' %}
            {{ field|add_class:"form-control dateinput" }}
            {% else %}
            {{ field|add_class:"form-control" }}
            {% endif %}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
      <br>
      {% for error in form.non_field_errors %}
      {{ error }}
      {% endfor %}
      <br>
      <div class="card-header with-border">
        <h3 class="card-title">Add Exercises</h3>
      </div>
      <table class="table">
      <td class="form-group{% if field.errors %} has-error{% endif %}">
        <select name="existing_exercises" required id="id_existing_exercises" class = "form-control">
          <option>
            ------
          </option>
        {% for exercise in exerciseSelect %}
          <option >
          {{ exercise }}
          </option>
        {% endfor %}
      </select>
      </td>

      <table class="table table-striped">
        <tr>
          <th>Description</th>
          <th>Sets</th>
          <th>Reps</th>
        </tr> 
         <tr>
          <td id="selected_exercise_description"></td>
          <td id="selected_exercise_sets"></td>
          <td id="selected_exercise_reps"></td>
         </tr>
      </table>
      <td>
        <a id="add-routineexercises" class="btn btn-info">Add Existing Exercise</a>
        <a id="add-routineexercises-empty" class="btn btn-info">Add New Exercise</a>
      </td>
      </table>
      <div class="card-header with-border">
        <h3 class="card-title">Routine Exercises</h3>
      </div>
      {{ formset.management_form }}
      <table id="formset" class="table">
        {% for routineexercises in formset %}
        {% if forloop.first %}
        <tr>
          {% for field in routineexercises.visible_fields %}
          <th>{{ field.label }}</th>
          {% endfor %}
        </tr>
        {% endif %}
        <tr >
          {% for field in routineexercises.visible_fields %}
          {% if field|widget_type == 'checkboxinput' %}
          <td class="text-center">{{ field }}</td>
          {% else %}
          <td class="form-group{% if field.errors %} has-error{% endif %}">
            {% if field|widget_type == 'dateinput' %}
            {{ field|add_class:"form-control dateinput" }}
            {% else %}
            {{ field|add_class:"form-control" }}
            {% endif %}
          </td>
          {% endif %}
          {% endfor %}
          {% for field in routineexercises.hidden_fields %}
          {{ field }}
          {% endfor %}
        </tr>
        {% if routineexercises.errors %}
        <tr>
          {% for error in routineexercises.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </tr>
        {% endif %}
        {% endfor %}
      </table>
      <p id="no-exercises" style="text-align: center">You haven't added any exercises to this Routine yet.</p>
      <button type="submit" class="btn btn-primary">{% if object %}Update{% else %}Create{% endif %}</button>
    </form>
  </div>
</div>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'vendor/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'vendor/js/bootstrap-datepicker.min.js' %}"></script>
<script>
    var exercises = '{{ exercises|escapejs }}'
    var exerciseData
    var parsedEx = jQuery.parseJSON(exercises)
    var sel_ex_desc = $('#selected_exercise_description')
    var sel_ex_sets = $('#selected_exercise_sets')
    var sel_ex_reps = $('#selected_exercise_reps')


    $('#id_existing_exercises').change( function() {
        for ( x in parsedEx['py/state']['_result_cache'])
        {
          exerciseData = parsedEx['py/state']['_result_cache'][x]['py/reduce'][2];
          var selectExercise = $('#id_existing_exercises')[0]['selectedOptions'][0]['label'];

          if(selectExercise == exerciseData.title)
          {
            break;
          }
        }
 
        sel_ex_desc.html(exerciseData.description)
        sel_ex_sets.html(exerciseData.sets)
        sel_ex_reps.html(exerciseData.reps)
     })

function cloneMore(selector, isEmpty) {
    var newElement = $(selector).clone(true);
    noExercise()
    var total = $('#id_routineexercises-TOTAL_FORMS').val();
    // var selectedExercise =
    newElement.css('display','table-row')
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total - 1) + '-','-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
        if (isEmpty == false){
          if( name=='routineexercises-'+total+'-title') $(this).attr({'name': name, 'id': id}).val(exerciseData.title).removeAttr('checked');
          if( name=='routineexercises-'+total+'-description') $(this).attr({'name': name, 'id': id}).val(exerciseData.description).removeAttr('checked');
          if( name=='routineexercises-'+total+'-reps') $(this).attr({'name': name, 'id': id}).val(exerciseData.reps).removeAttr('checked');
          if( name=='routineexercises-'+total+'-sets') $(this).attr({'name': name, 'id': id}).val(exerciseData.sets).removeAttr('checked');
        } else {
          if( isEmpty==true ) $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
        }
    });
    newElement.find('.dateinput').each(function() {
        $(this).attr("id", "").removeData().off();
        $(this).find('.add-on').removeData().off();
        $(this).find('input').removeData().off();
        $(this).datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            disableTouchKeyboard: true
          });
    });
    newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total - 1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
    });
    $('#id_routineexercises-TOTAL_FORMS').val(++total);
    $(selector).after(newElement);
}

  function noExercise(){
    var noEx = $('#no-exercises')
    
    noEx.css('display','none')
  }
$(function() {
  if( $('#id_routineexercises-INITIAL_FORMS').val() > 0){
    noExercise()
  }

  $('#formset tr:last').css('display','none')   
  $('.dateinput').datepicker({
    autoclose: true,
    format: 'yyyy-mm-dd',
    disableTouchKeyboard: true
  });
  $('.dateinput').attr('autocomplete', 'off');
  $('#add-routineexercises').click(function() {
    cloneMore('#formset tr:last', false);
  });
  $('#add-routineexercises-empty').click(function() {
    cloneMore('#formset tr:last', true);
  });
});
</script>
{% endblock %}

workouttracker/templates/workouttracker/runs_overview.html
{% extends 'workouttracker/base.html' %}
{% load humanize %}

{% block content_header %}
<h1>Runs
</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Home</a></li>
  <li class="breadcrumb-item active">Runs</li>
</ol>
{% endblock %}

{% block content %}
<div class="card">
<div class="card-header with-border">
  <h3 class="card-title"> Past Runs</h3>
</div>
<div class="card-body">
<table class="table table-striped">
  <tr>
    <th>Date</th>
    <th>Description</th>
    <th class="hidden-xs">Distance</th>
    <th class="hidden-xs">Time</th>
    <th class="hidden-xs"></th>
  </tr>
{% for run in runs %}
<tr>
  <td><a href="{{ run.get_absolute_url }}">{{ run.date }}</a></td>
  <td class="hidden-xs">{{ run.description }}</td>
  <td class="hidden-xs">{{ run.distance }} km</td>
  <td class="hidden-xs">{{ run.time }} minutes</td>
  <form id="delete_form_{{run.pk}}" method="post" action="{% url 'run_delete' run.pk %}">
    {% csrf_token %}
  </form>
  <td class="hidden-xs"><a href="#" onclick="document.getElementById('delete_form_{{run.pk}}').submit();" class="btn btn-primary">Delete</a></td>

{% endfor %}
</table>
</div>
<div class="card-footer">
  <a href="{% url 'run_create' %}" class="btn btn-primary">Create</a>
</div>
</div>
{% endblock %}